name: PR Benchmark
on:
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Run pytest-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: |
          uv venv
          uv sync

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run benchmark
        run: pytest --benchmark-only --benchmark-json output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '130%'
          comment-on-alert: true
          summary-always: true
          fail-on-alert: true
          auto-push: false
          alert-comment-cc-users: '@andnp'
